services:
  zitadel:
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:v2.67.2-debug"
    command: "start-from-init --masterkey \"MasterkeyNeedsToHave32Characters\" --tlsMode disabled"
    environment:
      - "ZITADEL_DATABASE_COCKROACH_MAXOPENCONNS=40"
      - "ZITADEL_DATABASE_COCKROACH_MAXIDLECONNS=30"
      - "ZITADEL_DATABASE_COCKROACH_MAXCONNLIFETIME=10m"
      - "ZITADEL_DATABASE_COCKROACH_MAXCONNIDLETIME=1m"
      # https://github.com/zitadel/zitadel/blob/7caa43ab2398356e63f5722594eac88d4ee99044/cmd/defaults.yaml#L112
      - "ZITADEL_DATABASE_COCKROACH_EVENTPUSHCONNRATIO=0.2" # default 0.2
      - "ZITADEL_DATABASE_COCKROACH_PROJECTIONSPOOLERCONNRATIO=0.135" # default 0.135
      - "ZITADEL_DATABASE_COCKROACH_HOST=cockroach-1"
      - "ZITADEL_DATABASE_COCKROACH_DATABASE=defaultdb"
      - "ZITADEL_DATABASE_COCKROACH_PORT=26257"
      - "ZITADEL_DATABASE_COCKROACH_ADMIN_USERNAME=root"
      # - "ZITADEL_DATABASE_COCKROACH_ADMIN_PASSWORD=''"
      - "ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_MODE=disable"
      - "ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_ROOTCERT=''"
      - "ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_CERT=''"
      - "ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_KEY=''"
      - "ZITADEL_DATABASE_COCKROACH_USER_USERNAME=zitadel"
      # - "ZITADEL_DATABASE_COCKROACH_USER_PASSWORD=''"
      - "ZITADEL_DATABASE_COCKROACH_USER_SSL_MODE=disable"
      - "ZITADEL_DATABASE_COCKROACH_USER_SSL_ROOTCERT=''"
      - "ZITADEL_DATABASE_COCKROACH_USER_SSL_CERT=''"
      - "ZITADEL_DATABASE_COCKROACH_USER_SSL_KEY=''"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_EXTERNALDOMAIN=zitadel.127.0.0.1.nip.io"
      - "ZITADEL_FIRSTINSTANCE_ORG_NAME=administration"
      - "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=Password1!"
      - "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=false"
      - "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS=dev@example.com"
      - "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED=true"
      - "ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/zitadel-machine-key/service-account-key.json"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1" # type 1 is JSON
      - "ZITADEL_METRICS_TYPE=otel"
      # - "ZITADEL_TRACING_TYPE=otel" # TODO: Add for tracing
      # - "ZITADEL_TRACING_ENDPOINT=tempo:4317" # TODO: Add for tracing
      - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=bcrypt"
      - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_COST=12" # default=14
      # - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=argon2id"
      # - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_TIME=1" # default=3
      # - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_MEMORY=47104" # default=32768
      # - "ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_THREADS=1" # default=4
      - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_ALGORITHM=bcrypt"
      - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_COST=12" # default=4
      # - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_ALGORITHM=argon2id"
      # - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_TIME=1" #  default=3
      # - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_MEMORY=47104" # default=32768
      # - "ZITADEL_SYSTEMDEFAULTS_SECRETHASHER_HASHER_THREADS=1" # default=4``
    mem_limit: "1g"
    ports:
      - "8080:8080"
    healthcheck:
      test: "ZITADEL_TLS_ENABLED=false zitadel ready"
      interval: "10s"
      timeout: "10s"
      retries: 10
      start_period: "30s"
    depends_on:
      - permissions
      - cockroach-init # condition: "service_completed_successfully"
    volumes:
      - "zitadel-machine-key:/zitadel-machine-key"
  permissions:
    restart: "no"
    image: "debian:bookworm-slim"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "chmod -R 777 /terraform; ls -lah /terraform; chmod -R 777 /zitadel-machine-key; ls -lah /zitadel-machine-key"
    volumes:
      - "../terraform:/terraform"
      - "zitadel-machine-key:/zitadel-machine-key"
    networks:
      - "zitadel"
  terraform:
    restart: "no"
    image: "hashicorp/terraform:latest"
    environment:
      - TF_VAR_concurrency=${TF_VAR_concurrency}
    depends_on:
      zitadel:
        condition: "service_healthy"
    volumes:
      - "../terraform:/terraform"
      - "zitadel-machine-key:/zitadel-machine-key"
    working_dir: "/terraform"
    entrypoint: "/terraform/terraform.sh"
    links:
      - "zitadel:zitadel.127.0.0.1.nip.io"
    networks:
      - "zitadel"
  cockroach-1:
    image: cockroachdb/cockroach:latest
    command:
      - start
      - --insecure
      - --advertise-addr=cockroach-1:26257
      - --join=cockroach-1:26257,cockroach-2:26257,cockroach-3:26257
    ports:
      - "26257:26257"
      - 8081:8080
    networks:
      - "zitadel"
  cockroach-2:
    image: cockroachdb/cockroach:latest
    command:
      - start
      - --insecure
      - --advertise-addr=cockroach-2:26257
      - --join=cockroach-1:26257,cockroach-2:26257,cockroach-3:26257
    networks:
      - "zitadel"
  cockroach-3:
    image: cockroachdb/cockroach:latest
    command:
      - start
      - --insecure
      - --advertise-addr=cockroach-3:26257
      - --join=cockroach-1:26257,cockroach-2:26257,cockroach-3:26257
    networks:
      - "zitadel"
  cockroach-init:
    image: cockroachdb/cockroach:latest
    command:
      - --host=cockroach-1:26257
      - init
      - --insecure
    depends_on:
      - cockroach-1
      - cockroach-2
      - cockroach-3
    networks:
      - "zitadel"

networks:
  zitadel:
    external: true
volumes:
  tfdata:
  zitadel-machine-key:
